"""
Static data for the /banana command.

Swap BANANA_IMAGES for local file paths (and attach with discord.File)
if you'd rather ship images inside the repo instead of linking them.
"""

from __future__ import annotations

BANANA_FACTS: list[str] = [
    "Bananas are berries, but strawberries aren't.",
    "Bananas float in water because they're less dense than water.",
    "A cluster of bananas is called a 'hand', and a single banana is a 'finger'.",
    "Bananas are naturally slightly radioactive due to their potassium-40 content.",
    "The banana plant is technically the world's largest herb, not a tree.",
    "Bananas are curved because they grow toward sunlight, away from the stem.",
    "There are over 1,000 varieties of bananas grown around the world.",
    "Bananas can help clean scratches off of old CDs and silverware.",
    "India produces more bananas than any other country on Earth.",
    "The wild ancestor of the banana contains large, hard seeds.",
    "Bananas release gases that help ripen other fruit placed near them.",
    "Uganda has the world's highest per-capita banana consumption.",
    "Bananas grow pointing upward, not hanging down, while on the plant.",
    "The banana plant has no trunk made of wood — it's made of tightly packed leaf stalks.",
    "Most commercial bananas are the Cavendish variety, which is seedless and sterile.",
    "The Cavendish banana can't reproduce sexually; every plant is a clone of another.",
    "Before the Cavendish, the dominant export banana was the Gros Michel, wiped out by disease.",
    "Bananas are technically classified as a fruit and, botanically, a berry.",
    "A banana plant produces fruit only once, then the stem is cut down for a new one to grow.",
    "It takes about 9 to 12 months for a banana plant to go from planting to harvest.",
    "Banana peels can be used as a natural fertilizer thanks to their potassium content.",
    "Bananas are one of the few fruits available year-round in most grocery stores.",
    "The word 'banana' likely comes from the Arabic word 'banan', meaning 'finger'.",
    "Bananas contain no fat, sodium, or cholesterol.",
    "Ecuador is one of the world's top banana exporters.",
    "Bananas ripen faster when placed next to apples due to ethylene gas.",
    "A single banana plant can produce a bunch weighing over 50 kilograms (110 lbs).",
    "Bananas are a good source of vitamin B6, vitamin C, and dietary fiber.",
    "Some banana varieties, like plantains, are usually cooked rather than eaten raw.",
    "Bananas were first cultivated in Southeast Asia thousands of years ago.",
    "Green (unripe) bananas contain more resistant starch than ripe, yellow ones.",
    "Banana fiber from the plant's stem can be woven into textiles and paper.",
    "The Guinness World Record for eating bananas is over 80 in a single sitting... painfully.",
    "Bananas are technically berries because they develop from a single flower with one ovary.",
    "In some cultures, banana leaves are used as eco-friendly, biodegradable plates.",
    "Bananas can help satisfy sugar cravings due to their natural sweetness.",
    "The average banana is about 75% water.",
    "China, the Philippines, and Indonesia are also among the world's largest banana producers.",
    "Bananas don't grow well in cold climates — they need warm, tropical conditions.",
    "Bananas are climacteric fruits, meaning they continue to ripen after being picked.",
    "A bunch of bananas is sometimes called a 'bunch' or a 'stem', containing multiple hands.",
    "The inside of a banana peel can be rubbed on mosquito bites to help reduce itching.",
    "Bananas were introduced to the Americas by Portuguese and Spanish colonizers.",
    "The 'string' on a banana is called a phloem bundle and helps carry nutrients to the fruit.",
    "Some banana plants can grow over 6 meters (20 feet) tall.",
    "Dried bananas are sometimes ground into banana flour, a gluten-free alternative.",
    "Bananas contain tryptophan, an amino acid the body uses to help produce serotonin.",
    "There's a museum in Sweden entirely dedicated to bananas.",
    "The banana emoji 🍌 was added to Unicode in 2010.",
    "Banana plants are technically perennial herbs, part of the genus Musa.",
    "Bananas can be used to make banana beer, a traditional drink in parts of East Africa.",
    "The average person in the US eats around 27 pounds of bananas per year.",
    "Bananas contain small amounts of natural sugars: glucose, fructose, and sucrose.",
    "Overripe bananas are ideal for baking because their starches have converted to sugar.",
    "Banana chips are typically made by frying or dehydrating thin slices of the fruit.",
    "Some banana varieties turn red or purple when ripe instead of yellow.",
    "The Red Dacca banana has a reddish-purple peel and a creamy, slightly sweet flesh.",
    "Blue Java bananas are sometimes called 'ice cream bananas' for their smooth texture.",
    "Bananas can be grown from suckers (side shoots) rather than seeds.",
    "A banana plant's 'trunk' is technically called a pseudostem.",
    "Bananas were once considered a luxury item in parts of Europe and North America.",
    "The first bananas sold in the U.S. were individually wrapped in foil as a novelty in 1876.",
    "Bananas are used in traditional medicine in some cultures to help soothe upset stomachs.",
    "A ripe banana's sweetness comes largely from its high sugar-to-starch ratio.",
    "Bananas can be frozen and blended to make a simple dairy-free 'nice cream'.",
    "The tallest banana plant on record grew over 12 meters (40 feet) tall in England.",
    "Banana fiber is strong enough to be woven into rope and even currency paper in Japan.",
    "Bananas are naturally free of gluten, making them safe for people with celiac disease.",
    "Costa Rica and Colombia are also major banana-exporting countries.",
    "Bananas were featured in early stop-motion cartoons as a classic slipping hazard gag.",
    "A banana's peel turns brown due to an enzymatic reaction called oxidation.",
    "Plantains are starchier and less sweet than dessert bananas, and usually cooked.",
    "The banana industry has historically influenced politics in parts of Central America.",
    "Bananas can help replenish electrolytes lost through sweating during exercise.",
    "Some farmers use banana peels as a natural polish for leather shoes.",
    "Bananas are propagated by cutting away and replanting the plant's underground rhizome.",
    "A group of banana plants growing together is sometimes called a banana grove or plantation.",
    "The scientific name for the common dessert banana is Musa acuminata.",
]

BANANA_IMAGES: list[str] = [
    "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e",
    "https://images.unsplash.com/photo-1571771019784-3ff35f4f4277",
    "https://images.unsplash.com/photo-1528825871115-3581a5387919",
    "https://images.unsplash.com/photo-1543218024-57a70143c369",
    "https://images.unsplash.com/photo-1587132137056-bfbf0166836e",
    "https://images.unsplash.com/photo-1603833665858-e61d17a86224",
]
